# Generated by Django 5.2 on 2025-06-10 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0004_organisationsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="DbtProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "project_type",
                    models.CharField(
                        choices=[("DBT_CLOUD", "dbt Cloud"), ("DBT_CORE", "dbt Core")],
                        default="DBT_CLOUD",
                        max_length=10,
                    ),
                ),
                ("dbt_cloud_api_key", models.TextField(blank=True, null=True)),
                (
                    "dbt_cloud_project_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dbt_cloud_job_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "git_repository_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("git_ssh_key", models.TextField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_org_related",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
