# Generated by Django 5.2 on 2025-06-11 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sources", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbtproject",
            name="dbt_cloud_job_id",
        ),
        migrations.RemoveField(
            model_name="dbtproject",
            name="dbt_cloud_project_id",
        ),
        migrations.RemoveField(
            model_name="dbtproject",
            name="git_repository_url",
        ),
        migrations.RemoveField(
            model_name="dbtproject",
            name="git_ssh_key",
        ),
        migrations.RemoveField(
            model_name="dbtproject",
            name="project_type",
        ),
        migrations.AddField(
            model_name="dbtproject",
            name="connection_type",
            field=models.CharField(
                choices=[("DBT_CLOUD", "dbt Cloud"), ("GITHUB", "GitHub")],
                default="DBT_CLOUD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dbtproject",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="dbtproject",
            name="dbt_cloud_account_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dbtproject",
            name="dbt_cloud_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dbtproject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
