# Generated by Django 5.2 on 2025-07-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sources", "0004_api_key_to_ssm"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbtproject",
            name="github_branch",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dbtproject",
            name="github_project_folder",
            field=models.CharField(
                blank=True,
                help_text="Path to the folder containing dbt_project.yml within the repository.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dbtproject",
            name="github_repository_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
