# Generated by Django 5.2 on 2025-07-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waitlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="team_size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
