# Generated by Django 5.2 on 2025-05-03 17:52

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("document", models.TextField()),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        dimensions=1536,
                        help_text="Embedding based on model documentation",
                    ),
                ),
                ("model_metadata", models.JSONField(blank=True, null=True)),
                (
                    "can_be_used_for_answers",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this embedding can be used for answering questions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Model Embedding",
                "verbose_name_plural": "Model Embeddings",
                "db_table": "model_embeddings",
            },
        ),
    ]
