# Generated by Django 5.2 on 2025-06-18 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("embeddings", "0002_update_embedding_dimensions"),
        ("embeddings", "0004_modelembedding_is_processing"),
    ]

    operations = []
