# Generated by Django 5.2 on 2025-06-10 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationSettings",
            fields=[
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to="accounts.organisation",
                    ),
                ),
                ("slack_bot_token", models.TextField(blank=True, null=True)),
                ("slack_signing_secret", models.TextField(blank=True, null=True)),
                ("slack_app_token", models.TextField(blank=True, null=True)),
                (
                    "llm_chat_provider",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "llm_chat_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("llm_api_key", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
