# Generated by Django 5.2 on 2025-06-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_organisationsettings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisationsettings",
            old_name="llm_api_key",
            new_name="llm_anthropic_api_key",
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="llm_embeddings_model",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'text-embedding-ada-002'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="llm_embeddings_provider",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'openai', 'google'",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="llm_google_api_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="llm_openai_api_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationsettings",
            name="llm_chat_model",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'gpt-4', 'gemini-pro'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationsettings",
            name="llm_chat_provider",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'openai', 'google', 'anthropic'",
                max_length=50,
                null=True,
            ),
        ),
    ]
