# Generated by Django 5.2 on 2025-06-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0005_rename_llm_api_key_organisationsettings_llm_anthropic_api_key_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationsettings",
            name="metabase_api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="metabase_database_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="metabase_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="metabase_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="snowflake_account",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="snowflake_database",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="snowflake_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="snowflake_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="snowflake_schema",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="snowflake_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organisationsettings",
            name="snowflake_warehouse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
