# Generated by Django 5.2 on 2025-06-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_organisationsettings_metabase_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationsettings",
            name="enabled_integrations",
            field=models.JSONField(
                default=list,
                help_text="List of enabled integration keys (e.g., ['snowflake', 'metabase'])",
            ),
        ),
    ]
