# Generated by Django 5.2 on 2025-06-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_organisationsettings_enabled_integrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationsettings",
            name="slack_team_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
