# Generated by Django 5.2 on 2025-06-21 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_organisationsettings_slack_team_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisationsettings",
            name="enabled_integrations",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="metabase_api_key",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="metabase_database_id",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="metabase_enabled",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="metabase_url",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="slack_app_token",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="slack_bot_token",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="slack_signing_secret",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="slack_team_id",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="snowflake_account",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="snowflake_database",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="snowflake_enabled",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="snowflake_password",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="snowflake_schema",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="snowflake_user",
        ),
        migrations.RemoveField(
            model_name="organisationsettings",
            name="snowflake_warehouse",
        ),
    ]
