# Generated by Django 5.2 on 2025-06-18 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0002_question_organisation"),
        ("workflows", "0002_update_embedding_dimensions"),
    ]

    operations = []
