# Generated by Django 5.2 on 2025-06-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0004_conversation_conversationpart_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationpart",
            name="actor",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("agent", "Agent"),
                    ("system", "System"),
                    ("llm", "LLM"),
                    ("tool", "Tool"),
                ],
                default="user",
                help_text="Who/what generated this part",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversationpart",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("message", "Message"),
                    ("intent_classification", "Intent Classification"),
                    ("llm_input", "LLM Input"),
                    ("llm_output", "LLM Output"),
                    ("tool_execution", "Tool Execution"),
                    ("tool_error", "Tool Error"),
                    ("slack_output", "Slack Output"),
                    ("slack_file_output", "Slack File Output"),
                    ("workflow_completion", "Workflow Completion"),
                    ("error", "Error"),
                    ("thinking", "Agent Thinking"),
                ],
                default="test",
                help_text="Type of message/interaction",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conversationpart",
            name="part_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user_message", "User Message"),
                    ("agent_response", "Agent Response"),
                    ("tool_call", "Tool Call"),
                    ("tool_result", "Tool Result"),
                    ("agent_thinking", "Agent Thinking"),
                    ("error", "Error"),
                    ("system", "System Message"),
                ],
                help_text="Legacy field - use actor and message_type instead",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="conversationpart",
            index=models.Index(fields=["actor"], name="conversatio_actor_942823_idx"),
        ),
        migrations.AddIndex(
            model_name="conversationpart",
            index=models.Index(
                fields=["message_type"], name="conversatio_message_29ecf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationpart",
            index=models.Index(
                fields=["actor", "message_type"], name="conversatio_actor_b307da_idx"
            ),
        ),
    ]
