# Generated by Django 5.2 on 2025-07-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0007_conversationpart_result_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="llm_chat_model",
            field=models.CharField(
                blank=True,
                help_text="Specific LLM model used for this conversation",
                max_length=100,
                null=True,
            ),
        ),
    ]
