# Generated by Django 5.2 on 2025-06-21 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0008_organisationsettings_slack_team_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "integration_type",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=20,
                    ),
                ),
                ("icon_url", models.URLField(blank=True, null=True)),
                ("documentation_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "configuration_schema",
                    models.JSONField(
                        default=dict,
                        help_text="JSON schema defining required configuration fields",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganisationIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Integration-specific configuration (non-sensitive)",
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        default=dict,
                        help_text="Encrypted credentials and sensitive data",
                    ),
                ),
                (
                    "last_test_result",
                    models.JSONField(
                        default=dict, help_text="Last connection test result"
                    ),
                ),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.integration",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["integration__name"],
                "unique_together": {("organisation", "integration")},
            },
        ),
    ]
