# Generated by Django 5.2 on 2025-06-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_remove_organisationsettings_enabled_integrations_and_more"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationintegration",
            name="integration_key",
            field=models.CharField(
                default="unknown",
                help_text="Key of the integration as defined in constants.py",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="organisationintegration",
            options={"ordering": ["integration_key"]},
        ),
        migrations.AlterUniqueTogether(
            name="organisationintegration",
            unique_together={("organisation", "integration_key")},
        ),
        migrations.RemoveField(
            model_name="organisationintegration",
            name="integration",
        ),
        migrations.DeleteModel(
            name="Integration",
        ),
    ]
