# Generated by Django 5.2 on 2025-06-22 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_alter_organisationintegration_options_and_more"),
        ("integrations", "0002_populate_integration_keys"),
    ]

    operations = []
