# Generated by Django 5.2 on 2025-06-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0003_merge_20250622_1806"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisationintegration",
            name="credentials",
        ),
        migrations.AddField(
            model_name="organisationintegration",
            name="credentials_path",
            field=models.CharField(
                blank=True,
                help_text="Path to credentials JSON object in Parameter Store, e.g., '/ragstar/org-{org_id}/integrations/{integration_key}/credentials'",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisationintegration",
            name="integration_key",
            field=models.CharField(
                default="unknown",
                help_text="Key of the integration as defined in constants.py",
                max_length=50,
            ),
        ),
    ]
