# Generated by Django 5.2 on 2025-06-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0004_replace_credentials_with_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationintegration",
            name="credentials_path",
            field=models.CharField(
                blank=True,
                help_text="Path to credentials JSON object in Parameter Store, e.g., '/ragstar/{environment}/org-{org_id}/integrations/{integration_key}/credentials'",
                max_length=255,
                null=True,
            ),
        ),
    ]
