# Generated by Django 5.2 on 2025-07-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0012_alter_organisationsettings_llm_anthropic_api_key_path_and_more",
        ),
        ("integrations", "0005_alter_organisationintegration_credentials_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPOAuthAuthorizationRequest",
            fields=[
                (
                    "request_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "client_id",
                    models.CharField(help_text="OAuth client ID", max_length=100),
                ),
                (
                    "redirect_uri",
                    models.CharField(help_text="Redirect URI", max_length=500),
                ),
                (
                    "response_type",
                    models.CharField(help_text="OAuth response type", max_length=20),
                ),
                (
                    "scope",
                    models.CharField(help_text="Requested scopes", max_length=500),
                ),
                (
                    "code_challenge",
                    models.CharField(help_text="PKCE code challenge", max_length=200),
                ),
                (
                    "code_challenge_method",
                    models.CharField(
                        default="S256",
                        help_text="PKCE code challenge method",
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="OAuth state parameter",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this request expires"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "MCP OAuth Authorization Request",
                "verbose_name_plural": "MCP OAuth Authorization Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MCPOAuthClient",
            fields=[
                (
                    "client_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("client_secret", models.CharField(max_length=100)),
                ("client_name", models.CharField(max_length=200)),
                (
                    "redirect_uris",
                    models.JSONField(
                        default=list, help_text="List of allowed redirect URIs"
                    ),
                ),
                (
                    "grant_types",
                    models.JSONField(
                        default=list, help_text="List of allowed grant types"
                    ),
                ),
                (
                    "response_types",
                    models.JSONField(
                        default=list, help_text="List of allowed response types"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        default="mcp:tools mcp:resources mcp:prompts",
                        help_text="OAuth scopes",
                        max_length=500,
                    ),
                ),
                (
                    "auto_registered",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this client was auto-registered",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization that this client is linked to (for auto-registered clients)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP OAuth Client",
                "verbose_name_plural": "MCP OAuth Clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MCPOAuthAuthorizationCode",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "user_data",
                    models.JSONField(help_text="User data for token generation"),
                ),
                (
                    "scopes",
                    models.JSONField(default=list, help_text="Requested scopes"),
                ),
                (
                    "code_challenge",
                    models.CharField(help_text="PKCE code challenge", max_length=200),
                ),
                (
                    "redirect_uri",
                    models.CharField(help_text="Redirect URI", max_length=500),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this code expires"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_codes",
                        to="integrations.mcpoauthclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP OAuth Authorization Code",
                "verbose_name_plural": "MCP OAuth Authorization Codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
