# Generated by Django 5.2 on 2025-05-03 17:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("path", models.CharField(max_length=1024)),
                (
                    "schema_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("database", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "materialization",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "depends_on",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("tests", models.JSONField(blank=True, null=True)),
                (
                    "all_upstream_models",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("meta", models.JSONField(blank=True, null=True)),
                ("raw_sql", models.TextField(blank=True, null=True)),
                ("compiled_sql", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "yml_description",
                    models.TextField(
                        blank=True,
                        help_text="Description from YML documentation",
                        null=True,
                    ),
                ),
                (
                    "yml_columns",
                    models.JSONField(
                        blank=True,
                        help_text="Columns from YML documentation",
                        null=True,
                    ),
                ),
                (
                    "interpreted_columns",
                    models.JSONField(
                        blank=True,
                        help_text="LLM-interpreted column descriptions",
                        null=True,
                    ),
                ),
                (
                    "interpreted_description",
                    models.TextField(
                        blank=True,
                        help_text="LLM-generated description of the model",
                        null=True,
                    ),
                ),
                ("interpretation_details", models.JSONField(blank=True, null=True)),
                (
                    "unique_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "DBT Model",
                "verbose_name_plural": "DBT Models",
                "db_table": "models",
            },
        ),
    ]
