# Generated by Django 5.2 on 2025-06-12 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sources", "0003_changed_account_id_to_bigint"),
        ("knowledge_base", "0002_model_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="dbt_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="data_sources.dbtproject",
            ),
        ),
    ]
